### ISSUE TITLE
Is more balanced partitioning plan for T5-3B-16GPUs possible?

### ISSUE THREAD

**Issue by pinxuezhao** [saareliad/FTPipe#7]
Hi~Thanks for your neat project!
I was trying to partition T5-3B model. When partitioning it on 8 GPUs, I  used 

python -m autopipe.partition t5 --model_name_or_path t5-3b --t5_task squad1 --lmhead --n_iter 10 --analysis_batch_size 4 --partitioning_batch_size 4 --ct trace_cache_t53b_512_4_op --cp prof_cache_t53b_512_4_op_ftpipe --precompute_masks --stateless_tied --lmhead --n_partitions 8 --L 8 16 24 --max_seq_length 512 --answer_max_seq_length 4 --partitioning_method mpipe --preset ftpipe --dont_use_async_meta_alg --save_memory_mode --special_blocks T5Block

and got a pretty balanced plan:
<img width="972" alt="スクリーンショット 2022-06-26 13 22 41" src="https://user-images.githubusercontent.com/106951017/175800623-54931f71-4f94-4521-91cf-b672da7e14f1.png">.

But when partitioning it on 16 GPUs, I used 

python -m autopipe.partition t5 --model_name_or_path t5-3b --t5_task squad1 --lmhead --n_iter 10 --analysis_batch_size 4 --partitioning_batch_size 4 --ct trace_cache_t53b_512_4_op --cp prof_cache_t53b_512_4_op_ftpipe --precompute_masks --stateless_tied --lmhead --n_partitions 16 --L 16 32 48 --max_seq_length 512 --answer_max_seq_length 4 --partitioning_method mpipe --preset ftpipe --dont_use_async_meta_alg --save_memory_mode --special_blocks T5Block

and got a less balanced plan:

<img width="1412" alt="スクリーンショット 2022-06-26 13 52 17" src="https://user-images.githubusercontent.com/106951017/175801380-3cda3d54-6faa-4538-955c-9eb2a053e8b1.png">.

I understand that T5-3B model has 24 encoders and 24 decoders, so when partitioning on 8 GPUs, each GPU can be assigned 3 encoders and 3 decoders, which is very similar to what FTPipe has done. When partitioning on 16 GPUs, however, by reading the partitioned model generated by FTPipe, I found that each GPU is roughly assigned 3 encoders or 3 decoders, resulting in a less balanced plan.

Question: Is it possible to get a more balanced partitioning plan for T5-3B-16GPUs using FTPipe?

**Comment by pinxuezhao** [comment]
I wonder whether I used it wrong or I have missed out anything. Any suggestion will be appreciated!

**Comment by saareliad** [comment]
Hi @pinxuezhao ,
How much memory do you have on the GPUs? 
(Currently, FTPipe has hardcoded numbers of RTX2080TI, I'd change it if you have higher mem)


Note that in this config 512-4 means that the decoder barely does any compute compared to encoder (encoder does >128x more compute) so intuitivly: a standard partitioning algorithm would want to push all decoders together - constrained by memory.


Before I dive into pipeline tips that come to my head, note that In this work, we explored only the pipeline parallel dimension for more partitioning opportunities (assuming that the expansion to data-parallelism, e.g., equally duplicating the pipeline is conceptually trivial). 
Nevertheless, for 16 GPUs at T5-3B you may want to check the combination with data parallelism, which has intuitively good partitioning - if data-paralllel communication/memory won't be a problem.


**So, 16 GPUs, T5-3B (assuming we want pipeline parallelism alone ):**
You may want to play with `--special_blocks` and `--L` which gives hints to the mpipe alg on granularity, since 24 major layers of course do not split nicely to 16 GPUs, splitting 24 (+24) layers then fine-graining (as mpipe would do with this config) is not ideal.
Note that putting  `--special_blocks T5Block` attempts to create `L` blocks by unifying adjacent `T5Block`s using a hint from the layer name.

For example, the first thing I'll try  is utilizing ratio between attention and FF in T5.
I do not remember the exact ratio in T5-3b (can easily check this), but for the sake of the intuition, referring to the T5 encoder:
if attention vs FF would have a 1:2 ratio, for example, a finer granularity can be achieved for this example: encoder: 24 blocks of attention, 24 blocks of FF, is equivalent to 64 "units", which given the ratio could split nicely to 16 - (4 "units" per GPU).
To check it I'd place both attention and FF as special blocks (has to be exact names from the code).
Then run a grid search and see if this yields something.

I'd also try to do it with layers-graph vs op-graph.
(The reason is that too-much op granularity is not ideal since it makes the profiling of memory consumption less accurate)

**Comment by pinxuezhao** [comment]
Thank you very much for your response!
The memory capacity for my GPU(A100) is 40 GB. It would be highly appreciated if you could inform me how to change the hardcoded memory capacity.

**Comment by saareliad** [comment]
https://github.com/saareliad/FTPipe/blob/c3d853080e0bebde50deef78892baf0f3663daf1/autopipe/autopipe/model_partitioning/heuristics.py#L327

**Comment by pinxuezhao** [comment]
Thanks very much!
Best regards.

**Comment by pinxuezhao** [comment]
Hi~Sorry to bother you again for this question.
I reset the memory threshold to 40 * 1e9, and changed the config to 512-128:

python -m autopipe.partition t5 --model_name_or_path t5-3b --t5_task squad1 --lmhead --n_iter 10 --analysis_batch_size 16 --partitioning_batch_size 16 --precompute_masks --stateless_tied --lmhead --n_partitions 16 --L 16 32 48 --max_seq_length 512 --answer_max_seq_length 128 --partitioning_method mpipe --preset ftpipe --dont_use_async_meta_alg --save_memory_mode --special_blocks T5LayerFF T5Attention --disable_op_profiling --output_file test_layer_graph_combine

but the resulting partitioning plan is still not very balanced:
<img width="1610" alt="スクリーンショット 2022-06-30 12 43 45" src="https://user-images.githubusercontent.com/106951017/176594518-383e0c4a-6e7d-4f1e-be7f-736ad637e2cb.png">

I also tried other special blocks, and the most balanced plan I got is:

python -m autopipe.partition t5 --model_name_or_path t5-3b --t5_task squad1 --lmhead --n_iter 10 --analysis_batch_size 16 --partitioning_batch_size 16 --precompute_masks --stateless_tied --lmhead --n_partitions 16 --L 16 32 48 --max_seq_length 512 --answer_max_seq_length 128 --partitioning_method mpipe --preset ftpipe --dont_use_async_meta_alg --save_memory_mode --special_blocks T5DenseReluDense --disable_op_profiling --output_file test_layer_graph_

<img width="1636" alt="スクリーンショット 2022-06-30 12 47 49" src="https://user-images.githubusercontent.com/106951017/176594968-7a4adc80-4715-4bb2-9b1b-ada1ca1dc070.png">

And by reading the python code generated, I noticed that this partitioning plan is 3 consecutive encoders per gpu or 3 consecutive decoders per gpu.  

Is it possible to get a more balanced plan other than 3 consecutive encoders(or decoders) per gpu? Maybe I have misused some commands? Any suggestions would be highly appreciated!

**Comment by saareliad** [comment]
For a sanity check, Try larger `L`s: Since in T5-3b the dense part is extremely large so it is most of the computation. If we split 24 dense-relu-dense layers FF layers of the encoder into 2 and set L>=48  (try higher numbers) then there should be a reasonably balanced split with 3 such FFs per GPU. (ignoring communication at the moment) (ignoring the fact  that this is a very long pipeline) (for simplicity, I'm currently ignoring the attention part)

I refer to these:

`.../T5DenseReluDense[DenseReluDense]/Linear[wi]`
`.../T5DenseReluDense[DenseReluDense]/Linear[wo]`
 (taken from  https://github.com/saareliad/FTPipe/blob/afdd20dad8119e8cf6b49c5eb0accbe13153fd91/models/partitioned/op_t5_3b_tied_lmheads_320_8_8p_bw12_async_squad1_mpipe.py#L837-L839)

so first thing I'd try this + increase L to larger numbers and see if this works when the partition is very fine-grained, as a sanity check.

Note that the [by_prefix  ](https://github.com/saareliad/FTPipe/blob/afdd20dad8119e8cf6b49c5eb0accbe13153fd91/autopipe/autopipe/model_partitioning/mixed_pipe/by_prefix.py) coarsening heuristic is just a heuristic for coarsening the graph and was used in case of a more convenient partitioning (merging adjacent similar blocks is for shortening the pipeline).
So may need to adapt it if you want to research this special pipeline partitioning.

Specifically, it could use enhancement in this case (supporting [nested coarsening](https://github.com/saareliad/FTPipe/blob/afdd20dad8119e8cf6b49c5eb0accbe13153fd91/autopipe/autopipe/model_partitioning/mixed_pipe/by_prefix.py#L105)) to avoid splitting the the decoders at all, or to mark that we want `.../T5DenseReluDense[DenseReluDense]/Linear[wo]` and not just `Linear`.
I think that more code would be needed here to fully explore this.

Eventually, I am aware that coarsening is the hardest thing in MPipe and is heuristical. I tried to design it so it could be possible to add new ways / replace ways to coarsen,  see:
https://github.com/saareliad/FTPipe/blob/afdd20dad8119e8cf6b49c5eb0accbe13153fd91/autopipe/autopipe/model_partitioning/mixed_pipe/coarsening.py#L34-L40

**Comment by saareliad** [comment]
Eventually, I'm not sure that for 16 GPUs this exploration for T5-3B is worth the effort in your case. (unless it is for research purposes, or for a very long fine-tuning expeirment)

Since with 8 GPUs, it is already efficient to fine-tune T5 with the alg presented here and in practical cases you need to repeat experiments several times (e.g., different seeds, hprams) - so running parallel experiments (i.e., "experiment parallelism") with 8 GPUs at a time (and in A100 case: even 4 or less) is probably even more practical than a specialized solution for 16 GPUs or even than more practical than simpler solutions as replicating the pipeline equally.

From my experience in data-center scale experiments - once you solved the memory problem efficiently - "experiment parallelism" is what's done in practice, given the latency for a single experiment is acceptable.

**Comment by pinxuezhao** [comment]
Thank you very much for your advice!
